In [28]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error



ModuleNotFoundError: No module named 'statsmodels'

In [2]:
data=pd.read_csv("Boston.csv")

In [3]:
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [11]:
x=data.iloc[:,:12].values
y=data.iloc[:,12].values

In [12]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [13]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [15]:
y_train

array([34.9,  7.5, 17.8, 50. , 21.2, 18.5, 26.4, 28.2, 33.1, 17.9, 37.9,
       19. , 13.9, 23. , 21.4, 21.7, 12.3, 12.7,  8.4, 19.4,  7.2, 20.8,
       37.3, 30.8, 19.5, 20.7, 13.2, 20.5, 21. ,  8.3, 24.1, 21.7, 13.4,
       20. , 10.5, 12.5, 18.7, 23.4, 31.2, 25. ,  8.4, 22.6, 13.9, 24.7,
       22.5, 19.7, 13.4, 12.6, 19.4, 14.1, 15.6, 17.4, 18.8, 24.5, 23.9,
       45.4, 37.2, 31.5, 17.5, 13.6, 35.1, 17.7, 14.3, 12.1, 20.4, 30.5,
       20.9, 19.6, 29.6, 22.1, 19.3, 31.7, 21.4, 29. , 36.4,  8.3, 21.8,
       33.3, 50. , 16.5, 22.5, 18.4, 50. , 14. , 21.9, 37.6, 25. , 10.9,
        7.4, 31.1, 23.8, 18.5,  7. , 32. , 23.6, 19.4, 24.8, 32.2, 19.6,
       27.5, 19.8, 18.8, 11.8, 29.1, 21.2, 14.5, 33.2, 32.9, 23.2, 46.7,
       23.7, 18. , 20.3, 14.1, 22.2, 26.6, 27.5, 22.4, 17.1, 29.9, 21.1,
       26.7, 19.1, 15.6, 23.3, 23.9, 19.7,  5. , 18.3, 37. , 21.9, 19.4,
       21.7, 15.6, 19.6, 20.6, 23.1, 11.3, 24. , 17.6, 24.4, 10.2, 16.2,
       19. , 15.1, 22.8, 50. , 19.3,  8.8, 22.9, 16

In [16]:
model =LinearRegression()

In [18]:
model.fit(x_train,y_train)

LinearRegression()

In [19]:
model.intercept_

38.372540729956285

In [20]:
model.coef_

array([-1.21871748e-01,  5.62152756e-02,  6.01575444e-02, -1.85827533e+01,
        3.74547427e+00, -6.06488013e-03, -1.62047557e+00,  3.32038067e-01,
       -1.35950201e-02, -9.70819990e-01,  9.45377558e-03, -5.11696058e-01])

In [22]:
model.score(x_train,y_train)

0.7223243604894007

In [23]:
y_pred=model.predict(x_test)

In [24]:
MSE=mean_squared_error(y_test,y_pred)

In [25]:
MSE

19.49073677933135

In [26]:
np.sqrt(MSE)

4.414831455370788